services:
  postgres:
    environment:
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    image: postgres:16.2
    volumes:
      - /root/data:/var/lib/postgresql/data
    restart: unless-stopped
  vault:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ${SERVER_SSL_KEY_STORE}:${SERVER_SSL_KEY_STORE}:ro
      - /root/logs:/var/lib/outsideworx/logs
    ports:
      - "443:443"
    restart: on-failure