x-common-args: &common-args
  SERVER_SSL_CERTIFICATE: ${SERVER_SSL_CERTIFICATE}
  SERVER_SSL_CERTIFICATE_PRIVATE_KEY: ${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}
x-common-certificate: &common-certificate
  ${SERVER_SSL_CERTIFICATE}:${SERVER_SSL_CERTIFICATE}
x-common-certificate-private-key: &common-certificate-private-key
  ${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}:${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}
services:
  come-in-and-find-out:
    build:
      args:
        NAME: come-in-and-find-out
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: come-in-and-find-out
    ports:
      - "9001:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  duckumbrella:
    build:
      args:
        NAME: duckumbrella
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: duckumbrella
    ports:
      - "9002:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  gaiapeeps:
    build:
      args:
        NAME: gaiapeeps
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: gaiapeeps
    ports:
      - "9003:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  igli:
    build:
      args:
        NAME: igli
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: igli
    ports:
      - "9004:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  outsideworx:
    build:
      args:
        NAME: outsideworx
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: outsideworx
    ports:
      - "9005:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  soupart:
    build:
      args:
        NAME: soupart
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: soupart
    ports:
      - "9006:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  soupkitchen:
    build:
      args:
        NAME: soupkitchen
        <<: *common-args
      dockerfile: Dockerfile.site
    container_name: soupkitchen
    ports:
      - "9007:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key