services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    image: postgres:16.2
    volumes:
      - /root/outsideworx/data:/var/lib/postgresql/data
    restart: unless-stopped
  vault:
    container_name: vault
    depends_on:
      - postgres
    env_file:
      - .env
    build: .
    volumes:
      - ${SERVER_SSL_CERTIFICATE}:${SERVER_SSL_CERTIFICATE}:ro
      - ${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}:${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}:ro
      - /root/outsideworx/logs:/tmp/outsideworx/logs
    ports:
      - "443:443"
    restart: on-failure