x-common-certificate: &common-certificate
  ${SERVER_SSL_CERTIFICATE}:/usr/local/apache2/conf/fullchain.pem
x-common-certificate-private-key: &common-certificate-private-key
  ${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}:/usr/local/apache2/conf/privkey.pem
services:
  come-in-and-find-out:
    build:
      args:
        NAME: come-in-and-find-out
      dockerfile: Dockerfile.site
    container_name: come-in-and-find-out
    ports:
      - "9001:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  duckumbrella:
    build:
      args:
        NAME: duckumbrella
      dockerfile: Dockerfile.site
    container_name: duckumbrella
    ports:
      - "9002:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  gaiapeeps:
    build:
      args:
        NAME: gaiapeeps
      dockerfile: Dockerfile.site
    container_name: gaiapeeps
    ports:
      - "9003:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  igli:
    build:
      args:
        NAME: igli
      dockerfile: Dockerfile.site
    container_name: igli
    ports:
      - "9004:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  outsideworx:
    build:
      args:
        NAME: outsideworx
      dockerfile: Dockerfile.site
    container_name: outsideworx
    ports:
      - "9005:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  soupart:
    build:
      args:
        NAME: soupart
      dockerfile: Dockerfile.site
    container_name: soupart
    ports:
      - "9006:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key
  soupkitchen:
    build:
      args:
        NAME: soupkitchen
      dockerfile: Dockerfile.site
    container_name: soupkitchen
    ports:
      - "9007:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key