FROM alpine/git AS fetcher
ARG NAME
RUN git clone --depth 1 https://github.com/outsideworx/${NAME}.git /site

FROM httpd:2.4-alpine
COPY --from=fetcher /site /usr/local/apache2/htdocs/

EXPOSE 80
CMD ["httpd-foreground"]