global:
  scrape_interval: 5s
scrape_configs:
  - job_name: loki
    static_configs:
      - targets: [ "host.docker.internal:3100" ]
  - job_name: sites
    metrics_path: /metrics.txt
    proxy_url: http://tinyproxy:8888
    scheme: https
    static_configs:
      - targets: [
        "come-in-and-find-out:80",
        "gaiapeeps:80"
      ]
    tls_config:
      insecure_skip_verify: true
  - job_name: vault
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8080" ]