global:
  scrape_interval: 1m
scrape_configs:
  - job_name: loki
    static_configs:
      - targets: [ "loki:3100" ]
  - job_name: sites
    metrics_path: /metrics.txt
    static_configs:
      - targets: [
        "come-in-and-find-out",
        "duckumbrella",
        "gaiapeeps",
        "igli",
        "outsideworx",
        "soupart",
        "soupkitchen"
      ]
  - job_name: vault
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "vault" ]