app:
  clients:
    ciafo:
      origin: "*"
      token: "test"
server:
  port: 8080
  ssl:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: